#!/bin/ksh

# IPv4
echo "-->IPv4<--"
IP=`ifconfig |grep inet|grep -v inet6|grep -v 127.0.0.1|grep -v 192.168.56.|cut -c 7-99|awk '{print $1 " " $3}'`
echo IP: $IP
GW=`route -n get default|grep gateway|awk '{print $2}'`
GWMAC=`arp -na|grep $GW")"|awk '{print $4}'`
echo GW: $GW @ $GWMAC "-->" `ping -c 2 $GW|grep "packet loss"|awk -F "," {'print $3'}`

for NSv4 in `grep nameserver /etc/resolv.conf|grep -v ":"|awk {'print $2'}` 8.8.8.8 8.8.4.4; do
  echo DNS: $NSv4 "-->" `ping -c 2 $NSv4|grep "packet loss"|awk -F "," {'print $3'}`
done


# IPv6
# I get so few opportunities to test this, it's kinda crappy
IPv6=`ifconfig |grep inet6|grep -v "inet6 f"|grep -v ::1|grep -v temporary|awk '{print $2}'`
if [ $IPv6 ]; then
  echo 
  echo "-->IPv6<--"
  echo IPv6: $IPv6 
  IPv6LL=`ifconfig |grep inet6|grep -v "inet6 2"|grep en0|grep -v ::1|grep -v temporary|awk '{print $2}'|awk -F "%" '{print $1}'`
  echo IPv6LL: $IPv6LL
  GWv6=`netstat -nr -f inet6|grep default|awk '{print $2}'|awk -F "%" '{print $1}'`
  GWMACv6=`ndp -an|grep $GWv6|awk '{print $2}'`
  echo GWv6: $GWv6 @ $GWMACv6 
  # "-->" `ping6 -c 2 $GWv6|grep "packet loss"|awk -F "," {'print $3'}`

  for NSv6 in `grep nameserver /etc/resolv.conf|grep ":"|awk {'print $2'}` ; do
    echo DNS: $NSv6 "-->" `ping6 -c 2 $NSv6|grep "packet loss"|awk -F "," {'print $3'}`
  done

#  ping6 -c 4 www.metafarce.com
fi

